module.exports = [
  {
    path: '/holike-hzero-board/anDengPage/replace',
    component: 'anDengPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/anDengPage/index',
    component: 'anDengPage/index',
    models: ["anDeng"],
    authorized: true,
    title: '安灯&产能看板',
  },
  {
    path: '/holike-hzero-board/drillingPage/replace',
    component: 'drillingPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/drillingPage/index',
    component: 'drillingPage/index',
    models: ["drilling"],
    authorized: true,
    title: '排钻数采看板',
  },
  {
    path: '/pub/holike-hzero-board/anDengPage/AnDengPage',
    component: 'anDengPage/AnDengPage',
    models: ["anDeng"],
    authorized: true,
    title: '安灯&产能',
  },
  {
    path: '/holike-hzero-board/kitPage/replace',
    component: 'kitPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/kitPage/index',
    component: 'kitPage/index',
    models: ["kitting"],
    authorized: true,
    title: '齐套查询看板',
  },
  {
    path: '/pub/holike-hzero-board/kitPage/kitQuery',
    component: 'kitPage/KitQuery',
    models: ["kitting"],
    authorized: true,
    title: '齐套查询',
  },
  {
    path: '/holike-hzero-board/equipmentRepairPage/replace',
    component: 'equipmentRepairPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/equipmentRepairPage/index',
    component: 'equipmentRepairPage/index',
    models: ["equipment"],
    authorized: true,
    title: '设备报修',
  },
  {
    path: '/holike-hzero-board/standingPage/replace',
    component: 'standingPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/standingPage/index',
    component: 'standingPage/index',
    models: ["standing", "eventform"],
    authorized: true,
    title: 'L1 站立式看板',
  },
  {
    path: '/holike-hzero-board/distribution/replace',
    component: 'distributionPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/distribution/index',
    component: 'distributionPage/index',
    models: ["distribution"],
    authorized: true,
    title: '机修人员分布看板',
  },
  {
    path: '/holike-hzero-board/doorPlankPage/replace',
    component: 'doorPlankPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/doorPlankPage/index',
    component: 'doorPlankPage/index',
    // models: ["device"],
    authorized: true,
    title: '门板车间电子看板',
  },
  {
    path: '/holike-hzero-board/doorPlankProducePage/index',
    component: 'doorPlankProducePage/index',
    models: ["doorPlankProduce"],
    authorized: true,
    title: '门板生产进度监控',
  },
  {
    path: '/holike-hzero-board/doorPlankOutputPage/index',
    component: 'doorPlankOutputPage/index',
    models: ["doorPlankOutput"],
    authorized: true,
    title: '门板产能报表',
  },
  {
    path: '/holike-hzero-board/kpiEqRepairPage/index',
    component: 'kpiEqRepairPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/kpiEqRepairPage/index',
    component: 'kpiEqRepairPage/index',
    models: ["kpiEqRepair"],
    authorized: true,
    title: '机修看板',
  },
  {
    path: '/holike-hzero-board/qualityPage/replace',
    component: 'qualityPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/qualityPage/index',
    component: 'qualityPage/index',
    models: ["quality"],
    authorized: true,
    title: '品质部看板',
  },
  {
    path: '/holike-hzero-board/standingThreePage/replace',
    component: 'standingThreePage/replace',
  },
  {
    path: '/pub/holike-hzero-board/standingThreePage/index',
    component: 'standingThreePage/index',
    models: ["standingThree"],
    authorized: true,
    title: 'L3 总经理看板',
  },
  {
    path: '/holike-hzero-board/standingTwoPage/replace',
    component: 'standingTwoPage/replace',
  },
  {
    path: '/pub/holike-hzero-board/standingTwoPage/index',
    component: 'standingTwoPage/index',
    models: ["standingTwo"],
    authorized: true,
    title: 'L2 站立式看板',
  },
  {
    path: '/holike-hzero-board/packingPage/index',
    component: 'packingPage/index',
    models: ["packing"],
    title: '包装报表',
  },
  {
    path: '/holike-hzero-board/openMaterialPage/index',
    component: 'openMaterialPage/index',
    models: ["openMaterial"],
    title: '开料报工厚度查询统计报表',
  },
  {
    path: '/holike-hzero-board/cabinetBackPage/index',
    component: 'cabinetBackPage/index',
    models: ["cabinetBack"],
    title: '柜体背板产能报表',
  },
  {
    path: '/holike-hzero-board/unqualifiedPage/index',
    component: 'unqualifiedPage/index',
    models: ["unqualified"],
    title: '不合格查询报表',
  },
  {
    path: '/holike-hzero-board/opProgressPage/index',
    component: 'opProgressPage/index',
    models: ["opProgress"],
    title: '工序加工进度监控报表',
  },
  {
    path: '/holike-hzero-board/missReportWorkPage/index',
    component: 'missReportWorkPage/index',
    models: ["missReportWork"],
    title: '漏报工查询报表',
  },
  {
    path: '/holike-hzero-board/reportWorkPage/index',
    component: 'reportWorkPage/index',
    models: ["reportWork"],
    title: '报工查询报表',
  },
  {
    path: '/holike-hzero-board/autoPackingPage/index',
    component: 'autoPackingPage/index',
    models: ["autoPacking"],
    title: '自动包装订单子订单包装数量统计报表',
  },
  {
    path: '/holike-hzero-board/devicePage/index',
    component: 'devicePage/index',
    models: ["device"],
    title: '设备MTBF&MTTR报表',
  },
  {
    path: '/holike-hzero-board/deviceChangePage/index',
    component: 'deviceChangePage/index',
    models: ["deviceChange"],
    title: '设备更换配件MTBF报表',
  },
  {
    path: '/holike-hzero-board/deviceMaintainPage/index',
    component: 'deviceMaintainPage/index',
    models: ["deviceMaintain"],
    title: '设备保养查询报表',
  },
  {
    path: '/holike-hzero-board/deviceCheckPage/index',
    component: 'deviceCheckPage/index',
    models: ["deviceCheck"],
    title: '设备点检查询报表',
  },
  {
    path: '/holike-hzero-board/batchOrderPage/index',
    component: 'batchOrderPage/index',
    models: ["batchOrder"],
    title: '批次订单标准工时计算明细报表',
  },
  {
    path: '/holike-hzero-board/boardAttrPage/index',
    component: 'boardAttrPage/index',
    models: ["boardAttr"],
    authorized: true,
    title: '板件属性报表',
  },
  {
    path: '/holike-hzero-board/prodAbnormalPage/index',
    component: 'prodAbnormalPage/index',
    models: ["prodAbnormal"],
    title: '生产异常问题分析报表',
  },
  {
    path: '/holike-hzero-board/equipmentMachiningPage/index',
    component: 'equipmentMachiningPage/index',
    models: ["equipmentMachining"],
    authorized: true,
    title: '设备加工报表',
  },
];
